defaults:
  - cfg_clinvar_long
  - _self_

hydra:
  mode: MULTIRUN
  sweep:
    dir: checkpoints/Clinvar_trm-ACT-torch
    subdir: ${hydra.job.override_dirname}
  sweeper:
    params:
      arch.hidden_size: 256,384
      arch.L_layers: 2,3
      arch.L_cycles: 2,3
      lr: 5e-4,3e-4
